// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxqvocnbfkhlovdwbvba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4cXZvY25iZmtobG92ZHdidmJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjAzMTEsImV4cCI6MjA2NTUzNjMxMX0.g7xtG0nIri-xNycMQFQ8VSYAO9pkJtLovrPmLNvudcs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);